/**
 * Canonical domain types — single source of truth.
 *
 * Hooks, seed data and pages MUST import these interfaces instead of
 * declaring page-local duplicates. Status enums use Finnish canonical
 * values everywhere (UI labels may differ, the stored value does not).
 */

/* ─── Shared status enums (Finnish canonical values) ─── */
export type ProjectStatus = 'Aktiivinen' | 'Suunniteltu' | 'Valmis' | 'Myöhässä';
export type WorkOrderPriority = 'Korkea' | 'Normaali' | 'Matala';
export type WorkOrderStatus = 'Avoin' | 'Käynnissä' | 'Odottaa' | 'Valmis' | 'Peruttu';
export type WorkAssignmentScope = 'people' | 'project_team';
export type TimeEntryStatus = 'Hyväksytty' | 'Odottaa' | 'Hylätty';
export type TimeEntryBreakSource = 'none' | 'manual' | 'automatic';
export type EmployeeStatus = 'Aktiivinen' | 'Lomalla' | 'Sairas' | 'Koulutuksessa' | 'Eroonnut';
export type EquipmentStatus = 'Käytössä' | 'Vapaa' | 'Huollossa' | 'Vuokralla';
export type CustomerType = 'Yritys' | 'Yksityinen' | 'Taloyhtiö';
export type CustomerStatus = 'Aktiivinen' | 'Epäaktiivinen';
export type CrmLeadStage = 'Uusi' | 'Tarjous tehty' | 'Neuvottelu' | 'Sopimus';
export type SafetyItemType = 'incident' | 'risk' | 'inspection' | 'training';
export type SafetyItemSeverity = 'Lievä' | 'Keskitasoinen' | 'Vakava';
export type AnnouncementPriority = 'Tärkeä' | 'Normaali' | 'Info';
export type DiaryStatus = 'Luonnos' | 'Valmis' | 'Lukittu';
export type TravelExpenseStatus = 'Odottaa' | 'Hyväksytty' | 'Hylätty';
export type SiteReceiptType =
  | 'work_acceptance'
  | 'delivery_receipt'
  | 'measurement_record'
  | 'waybill'
  | 'material_receipt'
  | 'other';
export type SiteReceiptStatus = 'draft' | 'signed' | 'voided';
export type SiteReceiptAttachmentKind = 'photo' | 'document' | 'signature';

/* ─── Domain interfaces ─── */
export interface Project {
  id: string;
  name: string;
  customer: string;
  customerId?: string;
  projectNumber?: string;
  status: ProjectStatus;
  startDate: string;
  endDate: string;
  progress: number;
  budget: number;
  spent: number;
  description?: string;
  location?: string;
  responsibleSupervisorId?: string;
  projectManagerId?: string;
  costCenter?: string;
  siteLatitude?: number;
  siteLongitude?: number;
  siteRadiusM?: number;
  archivedAt?: string;
  /** Auth users explicitly placed on this site/project. */
  memberUserIds?: string[];
  /** Resolved display names for memberUserIds. */
  memberNames?: string[];
}

export interface WorkOrder {
  id: string;
  title: string;
  projectId?: string;
  project: string;
  /** Legacy/summary display label generated by the database. */
  assignee: string;
  assigneeUserIds?: string[];
  assigneeNames?: string[];
  assignmentScope?: WorkAssignmentScope;
  dueDate: string;
  priority: WorkOrderPriority;
  status: WorkOrderStatus;
  description?: string;
  type?: string;
  workerNote?: string;
  startedAt?: string;
  completedAt?: string;
}

export interface TimeEntry {
  id: string;
  date: string;
  userId?: string;
  employeeId?: string;
  employee: string;
  projectId?: string;
  project: string;
  workOrderId?: string;
  hours: number;
  overtime: number;
  breakMinutes?: number;
  breakSource?: TimeEntryBreakSource;
  startTime?: string;
  endTime?: string;
  breakStartTime?: string;
  breakEndTime?: string;
  source?: string;
  description: string;
  status: TimeEntryStatus;
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  lockedAt?: string;
  payrollPeriodId?: string;
  /** View fields used by the Tuntikirjaukset page (not part of the core record). */
  dayName?: string;
  projectColor?: string;
  workType?: string;
  personId?: string;
  personName?: string;
  personInitials?: string;
}

export interface Employee {
  id: string;
  /** Linked Supabase Auth user. Empty for people who do not have an account yet. */
  userId?: string;
  name: string;
  role: string;
  department: string;
  phone: string;
  email: string;
  startDate: string;
  status: EmployeeStatus;
  hourlyCostCents?: number;
  employmentType?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  archivedAt?: string;
  /** Legacy display-only metrics retained until project assignments are normalized. */
  projects: number;
  hours: number;
  training: number;
  certifications: string[];
}

export interface Equipment {
  id: string;
  name: string;
  type: string;
  serial: string;
  location: string;
  status: EquipmentStatus;
  lastMaintenance: string;
  assetNumber?: string;
  model?: string;
  year?: number;
  acquisitionCostCents?: number;
  hourlyCostCents?: number;
  nextMaintenance?: string;
  currentProjectId?: string;
  responsibleUserId?: string;
  archivedAt?: string;
  lastService?: string;
  nextService?: string;
  hours?: number;
  maxHours?: number;
  image?: string;
}

export interface Customer {
  id: string;
  name: string;
  type: CustomerType;
  contactPerson: string;
  phone: string;
  email: string;
  address: string;
  businessId?: string;
  notes?: string;
  archivedAt?: string;
  projectCount: number;
  lastContact: string;
  status: CustomerStatus;
}

export interface CrmLead {
  id: string;
  name: string;
  company: string;
  customerId?: string;
  value: number;
  stage: CrmLeadStage;
  assignee: string;
  assigneeUserId?: string;
  probability?: number;
  source?: string;
  lostReason?: string;
  convertedProjectId?: string;
  lastActivityAt?: string;
  date: string;
}

export interface DiaryEntry {
  id: string;
  date: string;
  projectId?: string;
  project: string;
  author: string;
  weather: string;
  temperature: string;
  workers: number;
  workDescription: string;
  deliveries?: string;
  issues?: string;
  delays?: string;
  status?: DiaryStatus;
  approvedBy?: string;
  approvedAt?: string;
  lockedBy?: string;
}

export interface SafetyItem {
  id: string;
  type: SafetyItemType;
  title: string;
  date: string;
  projectId?: string;
  project?: string;
  description?: string;
  location?: string;
  severity?: SafetyItemSeverity;
  status: string;
  assignee?: string;
  assigneeUserId?: string;
  dueDate?: string;
  rootCause?: string;
  correctiveAction?: string;
  preventiveAction?: string;
  resolvedAt?: string;
  verifiedAt?: string;
  verifiedBy?: string;
  latitude?: number;
  longitude?: number;
}

export interface WasteEntry {
  id: string;
  date: string;
  projectId?: string;
  project: string;
  wasteType: string;
  amount: number;
  method: string;
  cost: number;
  unit?: string;
  notes?: string;
  destination?: string;
  receiptNumber?: string;
  hazardous?: boolean;
}

export interface DrivingLogEntry {
  id: string;
  date: string;
  userId?: string;
  driver: string;
  equipmentId?: string;
  vehicle: string;
  startAddress: string;
  endAddress: string;
  distance: number;
  purpose: string;
  projectId?: string;
  project?: string;
  startOdometerKm?: number;
  endOdometerKm?: number;
}

export interface TravelExpense {
  id: string;
  date: string;
  userId?: string;
  employee: string;
  projectId?: string;
  type: string;
  description: string;
  amount: number;
  status: TravelExpenseStatus;
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  attachmentPath?: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  author: string;
  date: string;
  priority: AnnouncementPriority;
}

export interface Message {
  id: string;
  sender: string;
  recipient: string;
  senderUserId?: string;
  recipientUserId?: string;
  subject?: string;
  content: string;
  timestamp: string;
  read: boolean;
}

export interface SiteReceiptAttachment {
  id: string;
  receiptId: string;
  kind: SiteReceiptAttachmentKind;
  fileName: string;
  storagePath: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: string;
}

export interface SiteReceipt {
  id: string;
  organizationId: string;
  projectId?: string;
  workOrderId?: string;
  project: string;
  title: string;
  type: SiteReceiptType;
  referenceNumber?: string;
  occurredAt: string;
  signerName: string;
  signerRole?: string;
  signerCompany?: string;
  notes?: string;
  status: SiteReceiptStatus;
  signedAt?: string;
  voidedAt?: string;
  voidReason?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  attachments: SiteReceiptAttachment[];
}
